####
#POST http://localhost:3000/auth/register
#Content-Type: application/json
#
#{
#  "email": "testuser213@gmail.com",
#  "password": "TestPassword123.",
#  "confirmPassword": "TestPassword123."
#}
####
#

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "testuser212@gmail.com",
  "password": "TestPassword123."
}
###

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyNjI4NDA5LCJleHAiOjE3ODI2MzIwMDl9.rU6kE4fWHpEL_hOsnuJmDkpyHwXg5Yc6EVnYbdrOYTA
###


####
#POST http://localhost:3000/wallets
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzIzMzk0LCJleHAiOjE3ODIzMjY5OTR9.XJG7bLJ_lgDw3fHFqT4hrHyMkG3JCcZGnv4diX545WE
#
#{
#  "currency": "BTC",
#  "network": "BITCOIN"
#}
####
#
####
#GET http://localhost:3000/wallets
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzIzMzk0LCJleHAiOjE3ODIzMjY5OTR9.XJG7bLJ_lgDw3fHFqT4hrHyMkG3JCcZGnv4diX545WE
####

