####
#POST http://localhost:3000/auth/register
#Content-Type: application/json
#
#{
#  "email": "testuser322@gmail.com",
#  "password": "TestPassword123.",
#  "confirmPassword": "TestPassword123."
#}
####

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "testuser322@gmail.com",
  "password": "TestPassword123."
}
###

###
POST http://localhost:3000/wallets/10/deposits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc4MzA5Mjc2NiwiZXhwIjoxNzgzMDk2MzY2fQ.je3VAVsZ8X6Uu-Me3jXI0pt2XDuQanaMFjZD7Xcxd4M

{
  "hash": "0xabc123",
  "amount": 500
}
###


####
#GET http://localhost:3000/auth/me
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyNjI4NDA5LCJleHAiOjE3ODI2MzIwMDl9.rU6kE4fWHpEL_hOsnuJmDkpyHwXg5Yc6EVnYbdrOYTA
####


####
#POST http://localhost:3000/wallets
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc4Mjg0MzMyMSwiZXhwIjoxNzgyODQ2OTIxfQ.wez7SEbd96pyZ9ZFHaI6s9J2r2XNwlXduA84o3HuNPE
#
#{
#  "currency": "BTC",
#  "network": "BITCOIN"
#}
####


####
#GET http://localhost:3000/wallets/1
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc4Mjc2NTA5NSwiZXhwIjoxNzgyNzY4Njk1fQ.xxPWVHMpdh10WSYDmteitwc7htujQ4UOQfiVAJAoanI
####

