services:
  redis:
    image: redis:7
    container_name: 0xpay-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    container_name: 0xpay-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: 0xpay_user
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: 0xpay_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: